blank_issues_enabled: true
contact_links:
    - name: â“ Support Question
      url: https://github.com/rtCamp/snapwp-helper/discussions
      about: For general help requests, create a new topic in Github Discussions
    - name: ğŸ”’ Security Issue
      url: https://github.com/rtCamp/snapwp-helper/blob/main/.github/SECURITY.md
      about: Please report security issues directly to our security team. DO NOT create a public issue.
    - name: ğŸ’¬ Community Discord Channel
      url: https://discord.gg/55h7WmYZff
      about: The WPGraphQL Discord is a great place to communicate in real-time, and SnapWP has a dedicated channel. Ask questions, discuss features, get to know other folks using SnapWP and WPGraphQL.
